# Generated by Django 6.0.5 on 2026-05-24 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0002_studio_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('completed', 'Completed')], default='active', max_length=20)),
                ('project_type', models.CharField(choices=[('poster', 'Poster'), ('video', 'Video'), ('campaign', 'Campaign'), ('content', 'Content'), ('other', 'Other')], default='other', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='studios.studio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=7)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='studios.studio')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('revision', 'Revision'), ('approved', 'Approved'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('revision', 'Revision'), ('approved', 'Approved'), ('completed', 'Completed')], max_length=20)),
                ('to_stage', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('revision', 'Revision'), ('approved', 'Approved'), ('completed', 'Completed')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_transitions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='projects.task')),
            ],
            options={
                'ordering': ['-transitioned_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.task')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='projects.tag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='projects.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_versions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.task')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['studio', 'status'], name='projects_pr_studio__d0fb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['studio', 'deadline'], name='projects_pr_studio__059e80_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['lead'], name='projects_pr_lead_id_416a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['studio', 'name'], name='projects_ta_studio__4541cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('studio', 'name'), name='unique_tag_name_per_studio'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'stage'], name='projects_ta_project_0f66fa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'priority'], name='projects_ta_project_a65709_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='projects_ta_assigne_ef384b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='projects_ta_deadlin_abbe13_idx'),
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['task', 'transitioned_at'], name='projects_st_task_id_0653fd_idx'),
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['actor'], name='projects_st_actor_i_bc5aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['task', 'uploaded_at'], name='projects_at_task_id_f1bad8_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by'], name='projects_at_uploade_e5fe30_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['task', 'tag'], name='projects_ta_task_id_26120b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasktag',
            constraint=models.UniqueConstraint(fields=('task', 'tag'), name='unique_tag_per_task'),
        ),
        migrations.AddIndex(
            model_name='taskversion',
            index=models.Index(fields=['task', 'version_number'], name='projects_ta_task_id_401796_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskversion',
            constraint=models.UniqueConstraint(fields=('task', 'version_number'), name='unique_version_per_task'),
        ),
    ]
